### ISSUE TITLE
Tutorials for docs

### ISSUE THREAD

**Issue by muellerdo** [frankkramer-lab/aucmedi#100]
## topics
- [ ] XAI
- [ ] transfer learning
- [ ] custom architecture
- [ ] basic structure / 3 pillars
- [ ] Inclusion of metadata (tables)
- [ ] ~ensemble learning~
- [ ] custom subfunction
- [ ] dataset loading -> introduction to io_interfaces and io_loaders
