### ISSUE TITLE
Inconsistency of DataGenerator class naming

### ISSUE THREAD

**Issue by muellerdo** [frankkramer-lab/aucmedi#137]
- [ ] Rename DataGenerator to Data_Generator
- [ ] Refractoring all DataGenerator calls
- [ ] update figure module
- [ ] update figure quickstart
