### ISSUE TITLE
Rework AutoML CLI arguments

### ISSUE THREAD

**Issue by muellerdo** [frankkramer-lab/aucmedi#151]
- [x] Make all parameters optional (non-required)
- [x] Expect file structure as default value
- [x] Identify interface automatically (if no csv in training/ and --path_data is None -> directory)
- [x] Rename input/output parameter to be more clearer

File structure:
```
working_dir/
    training/
    test/
    model/
    evaluation/
    preds.csv
```
