### ISSUE TITLE
AutoML Implementation

### ISSUE THREAD

**Issue by muellerdo** [frankkramer-lab/aucmedi#41]
- [x] Implementation of Pipeline Block: Training
- [x] Implementation of Pipeline Block: Inference
- [x] Implementation of Pipeline Block: Evaluation
- [x] Implementation of Pipeline Block: XAI
- [x] Try it out on a dataset
- [x] Implementation of CLI base
- [x] Implementation of Pipeline Block Integration in CLI
- [x] Unittesting for everyone
- [x] Dockerization
- [x] Packaging as binary for PyPI
- [x] Make an example
- [x] Documentation

**Comment by muellerdo** [comment]
Add xai_decoder parameter to config of pred module
- only supported for single model (minimal/standard)

**Comment by muellerdo** [comment]
Idea prediction mode:

rename path_imagedir to path_images:
- if path is a directory -> normal application
- if path contains a "," -> list of files -> split by ","
- if path is a file -> no input_interface and only passing to DataGenerator as [file] and image_format == None
