### ISSUE TITLE
Make AUCMEDI 3D avaible

### ISSUE THREAD

**Issue by muellerdo** [frankkramer-lab/aucmedi#50]
- [x] Update subfunction resize, padding & cropping 3d able (check shape in subfunction)
- [x] Check if subfunction standardize can transform volumes
- [x] Clean up architectures via 2D / 3D
- [x] Add 3D architectures
- [x] Add numpy loader for volumes/images 
- [x] Add npy to accepted formats
- [x] Parameter in DataGenerator to pass loader() with default to image_loader()
- [x] Add 3D augmentation volumenations (can we just switch ai module depending on 2D/3D?)
- [x] Modify ensembler.augmenting function
- [x] Add 3D unittesting for ensembler.augmenting 
- [x] Add volume support in unittesting
- [x] Rework DataGenerator to allow better image preparation for large 3D volumes

XAI shouldn't be able to run on 3D :/
