### ISSUE TITLE
setup github actions

### ISSUE THREAD

**Issue by muellerdo** [frankkramer-lab/aucmedi#99]
- [x] unittesting for requirements as well as setup (see MIScnn)
- [x] website / documentation
- [x] code coverage via codecov?
- [x] automatic pushing of github releases to PyPI?
